CREATE DATABASE spa03;

CREATE TABLE categoria(
    IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE noticia (
    IDNOTICIA INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(50) NOT NULL,
    NOTICIA TEXT NOT NULL,
    DTNOTICIA DATE NOT NULL,
    IDCATEGORIA INT NOT NULL,
    FOREIGN KEY (IDCATEGORIA) REFERENCES categoria (IDCATEGORIA)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;